# Generated by Django 5.2.6 on 2025-12-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
